services:
  hive-metastore:
    image: apache/hive:3.1.2
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_USER: root
      HIVE_METASTORE_PASSWORD: root
      HIVE_METASTORE_PORT: 9083
    ports:
      - "9083:9083"
    networks:
      - data-lake
    depends_on:
      - minio
    command: ["hive", "metastore"]

networks:
  data-lake:
    external: true
