version: "3.8"

services:
  minio:
    extends:
      file: docker-compose.minio.yml
      service: minio

  hive-metastore:
    extends:
      file: docker-compose-4hive.yml
      service: hive-metastore

  trino:
    extends:
      file: docker-compose.trino.yml
      service: trino

  rest:
    extends:
      file: docker-compose.minio.yml
      service: iceberg-rest

  mc:
    extends:
      file: docker-compose.minio.yml
      service: mc  

networks:
  data-lake:
    external: true

volumes:
  minio_data:
    driver: local
  hive-metastore-config:
    driver: local
  hive-metastore-data:
    driver: local
