version: "3.8"
services:
  spark:
    image: bitnami/spark
    container_name: spark
    ports:
      - "4040:4040"
    networks:
      - data-lake
    environment:
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 1
    #depends_on:
    #  - minio
    #  - hive-metastore
    volumes:
      - ./data/spark:/data

networks:
  data-lake:
    external: true