version: "3.8"
services:
  minio:
    extends:
      file: docker-compose.minio.yml
      service: minio

  hive-metastore:
    extends:
      file: docker-compose.hive.yml
      service: hive-metastore

  trino:
    extends:
      file: docker-compose.trino.yml
      service: trino

  #spark:
  #  extends:
  #    file: docker-compose.spark.yml
  #    service: spark
