services:
  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8080:8080"
    networks:
      - data-lake
    #depends_on:
    #  - minio
    #  - hive-metastore
    volumes:
      - ./configs/trino:/etc/trino

networks:
  data-lake:
    external: true